sudo: required
dist: trusty

# Enable C++ support
language: cpp

#before_install:
#  - sudo apt-get install -y some_package

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./test/tests

# Custom packages for different target compilers
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
          packages:
            - g++-5
            - cmake
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - kalakris-cmake
          packages:
            - clang-3.7
            - cmake
      env: COMPILER=clang++-3.7

