# Enable C++ support
language: cpp

## Compiler selection
#compiler:
#  - clang
#  - gcc

install:
  - export CXX=g++-5
  - export CC=gcc-5

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - test/test

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

